version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REDIS_ADDR: redis:6379
      REDIS_PWD: pass
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:latest
    command: ["redis-server", "--requirepass", "pass"]
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 2s
      timeout: 1s
      retries: 10
